name: orthomap
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy
  - scipy
  - pandas>=1.5.1
  - ete3
  - scanpy
  - seaborn
  - harmonypy
  - alive-progress
  - python-wget
  - pytest