name: orthomap
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy>=1.24.2
  - scipy>=1.10.1
  - pandas>=1.5.1
  - ete3>=3.1.2
  - anndata>=0.8.0
  - scanpy>=1.9.3
  - seaborn>=0.12.2
  - alive-progress>=3.0.1
  - python-wget>=3.2
  - pytest>=7.2.2
  - pip>=23.0.1
  - pip:
      - harmonypy>=0.0.9